# <center> Exploring Data About Colleges </center>

This is a markdown cell. Type something here!

...and **Code cells** (where you can type R code, see next cell).

In [7]:
# Press the Run button or Ctrl+Return (or Cmnd+Return for mac)
print("Lizi luvs MfA LA")

#you can also use a code cell as calculator
3*7+9

[1] "Lizi luvs MfA LA"

[1] 30

<div class="alert alert-block alert-danger">

The data set we will be exploring today is part of <a href="https://skewthescript.org/data-science-challenge">the After the Exam Data Science Challenge</a> (a collaboration of Skew the Script, Data Science 4 Everyone, North Carolina State Data Science Academy, and [CourseKata](coursekata.org)). **Please do not circulate.**

</div>

# Which colleges are worth the price of admission?

Does college pay off? We'll use from the US Department of Education's <a href="https://collegescorecard.ed.gov/data/">College Scorecard Database</a> to answer that question. 

In this notebook, you'll use R to create scatterplots and fit simple linear regression models to explore how certain colleges might be better investments than others.

**Run the code cell below to set up the Jupyter notebook. The data set we're using is called `colleges`.**

In [3]:
# run this code to load coursekata's library of R functions
suppressPackageStartupMessages({
    library(coursekata)
})

options(repr.matrix.max.cols = 1000)

# This command grabs data from a csv file stored in google docs
# and puts it in a data frame called college_dat
colleges <- read.csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQfYL84GVFzetxkmEsuMLCcN4QeWZikYEYGNr4ZbV4_dRLAUb_HPr021e0FAb-5sK4AQaHNbe3M7JW4/pub?gid=616759312&single=true&output=csv')

# This prints the first 6 rows of colleges
head(colleges)

  name                           city       state region   median_debt
1 University of Alaska Fairbanks Fairbanks  AK    Far West 11.000
2 Alabama A & M University       Normal     AL    South    15.250
3 Auburn University              Auburn     AL    South    17.500
4 Faulkner University            Montgomery AL    South    14.250
5 Alabama State University       Montgomery AL    South    17.500
6 University of Montevallo       Montevallo AL    South    15.815
  default_rate highest_degree ownership         locale     hbcu
1  8.5         Graduate       Public            Suburb     No
2 12.1         Graduate       Public            Small City Yes
3  2.6         Graduate       Public            Small City No
4  9.9         Graduate       Private nonprofit Small City No
5 12.8         Graduate       Public            Small City Yes
6  5.4         Graduate       Public            Suburb     No
  admission_policy        admit_rate SAT_avg online_only enrollment size
1 Standard                67.01      1138    No           4259      Medium
2 Standard                66.20       959    No           6614      Medium
3 Standard                44.00      1302    No          27907      Large
4 Standard                66.10      1068    No           1834      Small
5 Common App Direct Admit 97.00       938    No           3603      Small
6 Standard                53.90      1131    No           2186      Small
  net_price avg_cost net_tuition ed_spending_per_student avg_faculty_salary
1 10.510    19.135    8.601      18.087                   9.658
2 15.529    15.000    8.101       4.836                   7.599
3 24.018    24.000   16.865       8.361                  10.722
4 20.500    19.900   10.810       5.917                   5.926
5 19.534    14.000    9.302       9.579                   7.194
6 18.584    17.000    9.089      13.809                   7.623
  pct_PELL pct_fed_loan grad_rate pct_firstgen med_fam_income med_alum_earnings
1 22.74    20.42        38.7      39.88327     35.9670        43.728
2 70.95    75.04        30.0      36.58281     23.5530        41.000
3 13.43    29.80        79.0      17.26471     72.0310        65.000
4 50.09    63.84        36.5      43.00319     24.0375        43.000
5 73.68    78.05        33.0      34.34343     22.0805        35.000
6 39.18    55.37        55.0      32.52376     43.8130        35.400

## 1.0: Get to Know the Dataset (`colleges`)

The US Department of Education's <a href="https://collegescorecard.ed.gov/data/">College Scorecard Database</a> shows various metrics of cost, enrollment, size, student debt, student demographics, and alumni success. It describes almost every University, college, community college, trade school, and certificate program in the United States. The data is current as of the 2020-2021 school year. 

The vertical columns of the dataframe are called `variables`, and their elements are called `values`. For example, the variable `city` has values `Normal`, `Birmingham`, `Montgomery`, `Huntsville`, etc. 

The horizontal rows of the dataframe are called `observations`. For example, the first observation is `Alabama A & M University`, which is located in `AL` (Alabama), in the city of `Normal`, and has a median student debt of `$15,250`. For this dataframe, each observation describes a specific college.

**1.1:** Take a look at your <a href="https://docs.google.com/document/d/e/2PACX-1vQiqj-kw_eeGhZ3cupwpwMPO3tHbHOCRawvP7XWrUdUDsLCZw8T71Buoe6jfiKzB8d8z9Y2O_3Fo32O/pub">handout</a> which lists all the variables and a brief description for `colleges`. What variables are you interested in or curious about? Are there any variables that you are surprised to see? Any variables that you think should be in the dataset?

**1.2:** Lets look at some of the colleges you discussed in the opening question. Run the code below to print out the row for Idaho State University (go Bengals!)

Then let's edit the code to look at other colleges.

In [13]:
filter(colleges, name == "Idaho State University")

  name                   city      state region              median_debt
1 Idaho State University Pocatello ID    Rockies & Southwest 23.2
  default_rate highest_degree ownership locale     hbcu
1 8.4          Graduate       Public    Small City No
  admission_policy           admit_rate SAT_avg online_only enrollment size
1 Open Access / State Direct 100        1080    No          12614      Medium
  net_price avg_cost net_tuition ed_spending_per_student avg_faculty_salary
1 12.4      17.3     6           8.5                     8.5
  pct_PELL pct_fed_loan grad_rate pct_firstgen med_fam_income med_alum_earnings
1 41       39           58        41           45             45.6

**1.3:** Sometimes looking up a particular college is hard because of all the variation in how we can write the name (e.g., Idaho State University versus Idaho State or ISU). So we can also filter by state (abbreviation) to look up exactly the way a college is named in this data set.

In [16]:
filter(colleges, state == "ID")

  name                           city      state region
1 Boise Bible College            Boise     ID    Rockies & Southwest
2 Idaho State University         Pocatello ID    Rockies & Southwest
3 The College of Idaho           Caldwell  ID    Rockies & Southwest
4 Lewis-Clark State College      Lewiston  ID    Rockies & Southwest
5 Northwest Nazarene University  Nampa     ID    Rockies & Southwest
6 Brigham Young University-Idaho Rexburg   ID    Rockies & Southwest
7 University of Idaho            Moscow    ID    Rockies & Southwest
8 Boise State University         Boise     ID    Rockies & Southwest
  median_debt default_rate highest_degree ownership         locale     hbcu
1 18.000      8.0          Bachelors      Private nonprofit Suburb     No
2 23.200      8.4          Graduate       Public            Small City No
3 17.750      3.7          Graduate       Private nonprofit Suburb     No
4 11.276      9.2          Bachelors      Public            Small City No
5 16.500      2.1          Graduate       Private nonprofit Suburb     No
6  8.645      3.1          Bachelors      Private nonprofit Town       No
7 16.000      4.1          Graduate       Public            Town       No
8 14.286      4.3          Graduate       Public            Small City No
  admission_policy           admit_rate SAT_avg online_only enrollment size
1 Standard                    96.40     1060    No            103      Small
2 Open Access / State Direct 100.00     1080    No          12614      Medium
3 Standard                    48.35     1153    No           1100      Small
4 State Direct Admission      99.75      998    No           2613      Small
5 Standard                    76.83     1098    No           1220      Small
6 Standard                    97.01     1132    No          43660      Large
7 State Direct Admission      74.44     1116    No           6837      Medium
8 State Direct Admission      77.49     1135    No          16973      Medium
  net_price avg_cost net_tuition ed_spending_per_student avg_faculty_salary
1 14.639    16.884   10.400       8.500                  4.069
2 12.400    17.300    6.000       8.500                  8.500
3 21.412    45.607    7.819       8.053                  7.156
4 10.775    16.922    4.661       7.971                  6.523
5 21.647    42.068    9.917       5.686                  6.482
6  6.698    12.381    2.782       4.656                  8.266
7 13.964    21.525   10.208      12.959                  9.583
8 16.153    21.621    9.261       8.023                  8.321
  pct_PELL pct_fed_loan grad_rate pct_firstgen med_fam_income med_alum_earnings
1 50.00    34.00        50.00     40.00000     45.000         33.140
2 41.00    39.00        58.00     41.00000     45.000         45.600
3 26.00    56.17        66.06     26.80723     63.773         45.431
4 31.27    36.05        35.85     40.47014     31.207         41.741
5 30.15    52.85        62.31     33.88430     51.227         47.908
6 32.79    18.94        55.93     24.34898     42.100         49.281
7 27.30    35.47        59.47     31.78761     45.018         48.272
8 20.99    30.00        54.52     33.47085     42.915         43.100

**1.4:** One of the variables we are going to focus on is `default_rate`. 

Our goal today is to think about *which colleges are worth the price of admission?* One of the variables we are going to focus on is `default_rate`.   
>`default_rate` is the percent of school's borrowers in default on student loans (from recent cohorts). Includes students who graduate, transfer, or dropout.
- Why might we look at `default rate`? 
- Why might this question be relvant for *students*? 

✏️ ...

**1.5:** What does a low default rate mean? What does a high default rate mean?

✏️ ...

## 2.0: What Variables Are Related to `default rate`? *The `select()` Command*

What variables are you curious about? Let's take closer look. Run the code below to use the `select()` command.

In [21]:
# here's how to select a few variables to show from the colleges dataset
# add in default_rate and then run. 
select(colleges, name)

     name
1    University of Alaska Fairbanks
2    Alabama A & M University
3    Auburn University
4    Faulkner University
5    Alabama State University
6    University of Montevallo
7    University of Alabama at Birmingham
8    University of Alabama in Huntsville
9    The University of Alabama
10   Auburn University at Montgomery
11   Birmingham-Southern College
12   Huntingdon College
13   Jacksonville State University
14   University of West Alabama
15   Samford University
16   Spring Hill College
17   Troy University
18   Tuskegee University
19   University of South Alabama
20   University of Arkansas at Pine Bluff
21   Lyon College
22   Arkansas State University
23   University of Central Arkansas
24   Central Baptist College
25   University of the Ozarks
26   Harding University
27   Henderson State University
28   John Brown University
29   University of Arkansas at Little Rock
30   Ouachita Baptist University
⋮    ⋮
1027 Milwaukee School of Engineering
1028 Mount Mary University
1029 Northland College
1030 Ripon College
1031 Saint Norbert College
1032 University of Wisconsin-Madison
1033 University of Wisconsin-Milwaukee
1034 University of Wisconsin-Green Bay
1035 Viterbo University
1036 University of Wisconsin-Stout
1037 University of Wisconsin-Eau Claire
1038 University of Wisconsin-La Crosse
1039 University of Wisconsin-Oshkosh
1040 University of Wisconsin-River Falls
1041 Wisconsin Lutheran College
1042 Maranatha Baptist University
1043 Marshall University
1044 University of Charleston
1045 West Liberty University
1046 West Virginia State University
1047 West Virginia University
1048 West Virginia University Institute of Technology
1049 West Virginia Wesleyan College
1050 Wheeling University
1051 Fairmont State University
1052 Concord University
1053 Alderson Broaddus University
1054 Bluefield State College
1055 Bethany College
1056 University of Wyoming

**2.1:** Add other variables to the `select()` function in the code cell above (you can refer to the <a href="https://docs.google.com/document/d/e/2PACX-1vQiM-BanJDDimx02JdYyx_WFkrkwUgHMvFKwXJo3FoISulnRsn459E4Kff9ZD_lM5pWrfilRWxSylQ4/pub">handout</a>). 

(If you want to arrange the data frame in order by a certain variable, you can also pipe on, `%>%` the `arrange()` function. We can do an example together.)

**2.2:** Start to look for patterns or relationships in the data. 

- What do you notice about colleges with really low default rates or really high default rates? 
- Is there anything that surprises you? 
- What questions do you have?

✏️ ...

**2.3:** What other variables might help us predict the loan default rate of a university? What relationship do you think they have? Write a **hypothesis** for one of your variables. An example is shown below.

> **Example hypothesis:** `avg_cost` might be important for predicting `default_rate`. I think colleges with *higher* `avg_cost` will have a *higher* `default_rate`.

We can write this hypothesis as a word equation **default_rate = avg_cost + other stuff**

📝 On the back of your handout, write some hypotheses that you want to explore as word equations. Sketch what you expect those relationships to look like. 📝

## 3.0: Explore Your Hypothesis *The `gf_point()` Command*

**3.1:** Let's create a scatter plot to explore our hypothesis. Edit the code below, adding variable names -- `default_rate` and the predictor variable you picked for your hypothesis. 

We need to add our variables into the code below to create a scatter plot. Add your variables -- we want to model `default_rate` and *some other variable that you

In [41]:
# add your variables to the code below to explore your hypothesis
gf_point( ~ , data = colleges)

**3.6:** What does your scatter plot tell you about your hypothesis? How does your hypothesis compare to your neighbors?

✏️ ...

**3.7:** Keep playing! Can you find the best predictor for a college's `default_rate`?

## 4.0: *Modeling* `default_rate`
Can you create a function to help us predict `default_rate`?

**4.1:** What do you think a *good* model for your data should look like? How would you decide if a model is good or not? 

✏️ ...

**4.2:** You can tinker with *y-intercept* and *slope*. Edit and run the code below to try to plot a line that could model the data.

Try it out in the code cell below.

In [ ]:
gf_point(default_rate ~ avg_cost, data = colleges) %>%
  gf_abline(intercept = 70, slope = 0, color = "blue")

**4.3:** Maybe you want to write your own function or try non-linear functions. You can create a custom function and add it to your graph. 

Try it out in the code cell below.

In [ ]:
# create your own function
my_function <- function(X){ .10x^2 }

gf_point(default_rate ~ avg_cost, data = colleges, color = "orange") %>%
  gf_function(my_function, color = "purple")

**4.4:** Or maybe you just want to graph the best-fitting linear function to our data. *Can you use any of the code commands above to try to find the equation of the best-fitting linear function?

In [ ]:
gf_point(default_rate ~ avg_cost, data = colleges, color = "orange") %>%
  gf_lm()

# Obligatory Plug: CourseKata Gates Foundation High School Stats Teacher Fellowship!

<img src="https://cdn.prod.website-files.com/6789c29ed0bff3679af53e2c/69d684e2f277d6aab4c0d6f8_HSfellowshipFlyer.png" width = 80%>

[Learn More](https://www.coursekata.org/news-announcements/2026-27-coursekata-fellowship-for-high-school-teachers)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=59b6ca27-b1c0-4000-9d61-7dbd635c3df1' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>